# golangci-lint configuration for NetSpy
version: 2

run:
  timeout: 5m
  tests: true

linters:
  enable:
    # Default linters (already enabled)
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

    # Additional useful linters
    - misspell
    - gosec
    - nilerr
    - unconvert
    # unparam disabled - produces false positives for future-proofed error returns

formatters:
  enable:
    - gofmt
    - goimports

linters-settings:
  errcheck:
    check-blank: true

  gosec:
    excludes:
      - G204  # Subprocess with variable (needed for network commands)
      - G304  # File path from variable (needed for config)

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
    # populateARPTable functions return error for future extensibility
    - text: "result 0 \\(error\\) is always nil"
      linters:
        - unparam
      source: "func populate.*ARPTable"
